FROM williamyeh/ansible:debian7

WORKDIR /tmp
COPY  .  /tmp/ansible-shell-users

RUN echo 127.0.0.1 > inventory

RUN ansible-playbook -i inventory ansible-shell-users/tests/provision.yml --connection=local --sudo
